/* eslint-disable @typescript-eslint/no-magic-numbers,unicorn/prefer-module */
module.exports = {
  'array-bracket-newline': [
    'error',
    {
      minItems: 3,
      multiline: true,
    },
  ],
  'array-callback-return': 'error',
  'array-element-newline': [
    'error',
    {
      minItems: 3,
      multiline: true,
    },
  ],
  'arrow-body-style': 'error',
  'arrow-parens': ['error', 'as-needed'],
  'arrow-spacing': 'error',
  'block-spacing': 'error',
  'brace-style': 'off',
  'camelcase': 'error',
  'class-methods-use-this': 'warn',
  'comma-dangle': ['error', 'always-multiline'],
  'comma-spacing': 'error',
  'comma-style': 'error',
  'complexity': 'off',
  'constructor-super': 'error',
  'curly': ['error', 'multi-line'],
  'default-case': 'warn',
  'default-case-last': 'error',
  'default-param-last': 'off',
  'dot-notation': 'off',
  'eol-last': 'error',
  'eqeqeq': ['error', 'smart'],
  'func-call-spacing': 'off',
  'func-name-matching': 'error',
  'func-style': [
    'error',
    'declaration',
    {
      allowArrowFunctions: true,
    },
  ],
  'generator-star-spacing': 'error',
  'grouped-accessor-pairs': 'error',
  'guard-for-in': 'error',
  'id-blacklist': 'error',
  'id-length': 'error',
  'id-match': 'error',
  'indent': ['error', 2],
  'jsx-quotes': ['error', 'prefer-single'],
  'key-spacing': 'error',
  'keyword-spacing': 'off',
  'lines-around-comment': 'error',
  'lines-between-class-members': 'off',
  'max-classes-per-file': ['error', 1],
  'max-depth': ['error', 4],
  'max-len': [
    'error',
    {
      code: 80,
      ignoreComments: true,
      ignoreRegExpLiterals: true,
      ignoreStrings: true,
      ignoreTemplateLiterals: true,
      ignoreTrailingComments: true,
      ignoreUrls: true,
    },
  ],
  'max-lines': ['error', 500],
  'max-lines-per-function': ['warn', 25],
  'max-nested-callbacks': 'error',
  'max-params': ['error', 6],
  'new-cap': 'error',
  'new-parens': 'error',
  'newline-per-chained-call': [
    'error',
    {
      ignoreChainWithDepth: 2,
    },
  ],
  'no-alert': 'error',
  'no-array-constructor': 'off',
  'no-bitwise': 'error',
  'no-caller': 'error',
  'no-cond-assign': 'error',
  'no-console': 'warn',
  'no-const-assign': 'error',
  'no-continue': 'error',
  'no-debugger': 'error',
  'no-dupe-class-members': 'off',
  'no-duplicate-imports': 'off',
  'no-else-return': 'error',
  'no-empty': 'error',
  'no-empty-function': 'off',
  'no-eq-null': 'error',
  'no-eval': 'error',
  'no-extend-native': 'error',
  'no-extra-bind': 'error',
  'no-floating-decimal': 'error',
  'no-invalid-this': 'off',
  'no-lone-blocks': 'error',
  'no-lonely-if': 'error',
  'no-loop-func': 'off',
  'no-magic-numbers': 'off',
  'no-mixed-operators': 'off',
  'no-multi-assign': 'error',
  'no-multi-spaces': 'error',
  'no-multi-str': 'error',
  'no-multiple-empty-lines': 'error',
  'no-negated-condition': 'error',
  'no-nested-ternary': 'error',
  'no-new': 'error',
  'no-new-wrappers': 'error',
  'no-param-reassign': 'error',
  'no-redeclare': 'off',
  'no-return-assign': 'error',
  'no-return-await': 'off',
  'no-self-compare': 'error',
  'no-shadow': [
    'error',
    {
      hoist: 'all',
    },
  ],
  'no-tabs': 'error',
  'no-template-curly-in-string': 'error',
  'no-throw-literal': 'off',
  'no-trailing-spaces': 'error',
  'no-undef-init': 'off',
  'no-underscore-dangle': 'error',
  'no-unmodified-loop-condition': 'error',
  'no-unneeded-ternary': 'error',
  'no-unsafe-finally': 'error',
  'no-unsafe-optional-chaining': 'error',
  'no-unused-expressions': 'off',
  'no-unused-labels': 'error',
  'no-unused-vars': 'off',
  'no-useless-catch': 'error',
  'no-useless-computed-key': 'error',
  'no-useless-concat': 'error',
  'no-useless-constructor': 'off',
  'no-useless-rename': 'error',
  'no-useless-return': 'error',
  'no-var': 'error',
  'no-whitespace-before-property': 'error',
  'nonblock-statement-body-position': 'error',
  'object-curly-newline': 'error',
  'object-curly-spacing': 'off',
  'object-property-newline': 'error',
  'object-shorthand': [
    'error',
    'methods',
    {
      avoidExplicitReturnArrows: true,
    },
  ],
  'one-var': ['error', 'never'],
  'operator-assignment': 'error',
  'padding-line-between-statements': 'off',
  'prefer-arrow-callback': 'error',
  'prefer-arrow/prefer-arrow-functions': 'off',
  'prefer-const': 'error',
  'prefer-destructuring': 'warn',
  'prefer-exponentiation-operator': 'error',
  'prefer-object-spread': 'error',
  'prefer-regex-literals': 'warn',
  'prefer-rest-params': 'error',
  'prefer-spread': 'error',
  'prefer-template': 'error',
  'quote-props': ['error', 'consistent-as-needed'],
  'quotes': [
    'error',
    'single',
    {
      avoidEscape: true,
    },
  ],
  'radix': 'error',
  'require-await': 'error',
  'semi': 'error',
  'sort-imports': 'off',
  'sort-keys': 'off',
  'sort-keys-fix/sort-keys-fix': 'warn',
  'space-before-blocks': 'error',
  'space-before-function-paren': 'off',
  'space-infix-ops': 'off',
  'spaced-comment': 'error',
  'switch-colon-spacing': 'error',
  'symbol-description': 'error',
  'template-curly-spacing': 'error',
  'use-isnan': 'error',
  'valid-typeof': 'off',
  'vars-on-top': 'warn',
  'yield-star-spacing': 'error',
  'yoda': 'error',
};
